version = getSubprojectVersion(project)

loom {
	accessWidenerPath = file("src/main/resources/fabric-resource-loader-v1.classtweaker")
}

moduleDependencies(project, ['fabric-api-base'])

testDependencies(project, [
	':fabric-lifecycle-events-v1',
	':fabric-api-base',
	':fabric-gametest-api-v1',
	':fabric-resource-loader-v1'
])

// Setup 3 test mods used for testing resource sorting
sourceSets {
	testmodA
	testmodB
	testmodC
}

[sourceSets.testmodA, sourceSets.testmodB, sourceSets.testmodC].each { sourceSet ->
	dependencies {
		testmodImplementation sourceSet.output
	}
	rootProject.dependencies {
		testmodImplementation sourceSet.output
	}

	tasks.register("${sourceSet.name}Jar", Jar) {
		from sourceSet.output
		archiveBaseName.set(sourceSet.name)
	}
}

//rootProject.allprojects.each { p ->
//	if (p.extensions.findByName("loom") == null) {
//		return // Skip over the meta projects
//	}

	neoForge.mods.register("fabric-resource-loader-v0-testmod-a") {
		sourceSet sourceSets.testmodA
	}
	neoForge.mods.register("fabric-resource-loader-v0-testmod-b") {
		sourceSet sourceSets.testmodB
	}
	neoForge.mods.register("fabric-resource-loader-v0-testmod-c") {
		sourceSet sourceSets.testmodC
	}
//}

//loom.nestJars(tasks.named("testmodJar"), project.files(
//	tasks.testmodAJar,
//	tasks.testmodBJar,
//	tasks.testmodCJar
//))
