implementationVersion=3.0.0

versionMc=26.1.2
versionNeoForge=26.1.2.73
versionForgifiedFabricLoader=2.5.75+0.18.4+26.1

curseForgeId=889079
modrinthId=Aqlf1Shp
githubRepository=Sinytra/ForgifiedFabricAPI
# This is the branch the release tag will be created from
publishBranch=26.1
