implementationVersion=3.2.0

versionMc=26.1.2
versionNeoForge=26.1.2.76
versionForgifiedFabricLoader=2.5.83+0.19.3+26.1.2

curseForgeId=889079
modrinthId=Aqlf1Shp
githubRepository=Sinytra/ForgifiedFabricAPI
# This is the branch the release tag will be created from
publishBranch=26.1.2
