version = getSubprojectVersion(project)

loom {
	accessWidenerPath = file("src/client/resources/fabric-renderer-indigo.classtweaker")
}

moduleDependencies(project, [
	'fabric-api-base',
	'fabric-renderer-api-v1',
	'fabric-rendering-v1'
])

sourceSets {
	main {
		java {
			srcDir 'src/mixinConfig/java'
		}
	}
}

dependencies {
	interfaceInjectionData project(':fabric-renderer-api-v1')
}
