import net.fabricmc.fabric.impl.build.FabricApiBuildUtils

plugins {
	id "fabric-api.root-versioning"
	id "fabric-api.java"
	id "fabric-api.lint"
	id "fabric-api.loom"
	id "fabric-api.validation"
	id "fabric-api.root-testing"
	id "fabric-api.root-publishing"
}

tasks.named("validateModules") {
	enabled = false
}

loom {
	accessWidenerPath = file("gradle/javadoc.classtweaker")
}

configurations {
	nestedJars {
		transitive = false
	}
}

def includedModuleProjects = rootProject.allprojects.findAll {
	FabricApiBuildUtils.isFabricModule(it) && it != project
}

dependencies {
	for (def moduleProject : includedModuleProjects) {
		api project(path: moduleProject.path)

		if (!FabricApiBuildUtils.DEV_ONLY_MODULES.contains(moduleProject.name)) {
			nestedJars project(moduleProject.path)
		}
	}
}

loom {
	nestJars(tasks.named("jar"), configurations.nestedJars)
	uncompressNestedJars = true
}

tasks.register("checkNoDuplicateFiles", Zip) {
	inputs.files configurations.nestedJars
	destinationDirectory = layout.buildDirectory.dir("test")

	from {
		configurations.nestedJars.files.collect { zipTree(it) }
	}

	exclude 'META-INF/**'
	exclude 'fabric.mod.json'
}

check.dependsOn "checkNoDuplicateFiles"
