version = getSubprojectVersion(project)

loom {
	accessWidenerPath = file('src/main/resources/fabric-convention-tags-v2.classtweaker')
}

moduleDependencies(project, [
	'fabric-api-base',
	'fabric-lifecycle-events-v1'
])

testDependencies(project, [
	':fabric-lifecycle-events-v1',
])

sourceSets {
	main {
		resources.srcDir 'src/generated/resources'
	}
}

//fabricApi {
//	configureDataGeneration {
//		outputDirectory = file("src/generated/resources")
//		strictValidation = true
//		createSourceSet = true
//		modId = "fabric-convention-tags-v2-datagen"
//	}
//}

dependencies {
//	datagenImplementation project(path: ":fabric-data-generation-api-v1")
}

loom {
//	runs {
//		datagen {
//			name "Data Generation"
//			ideConfigGenerated = true
//		}
//	}
}

//generateResources.dependsOn runDatagen
